name: Netlify Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install and build
        run: npm install && npm run build
      
      - name: Deploy
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build'
          production-branch: master
          deploy-message: '${{ github.event.head_commit.message }}'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}